### ISSUE TITLE
No values are displayed on VSCode after running simulation

### ISSUE THREAD

**Issue by rameloni** [Kuree/hgdb-debugger#12]
Hello, I tried to execute the `hgdb-vscode` debugger but nothing is displayed.
![hgdb-debugger-not-working](https://github.com/Kuree/hgdb-debugger/assets/92363051/97b47499-5e6a-415f-8353-73f1adaf7b52)

I made me sure that the symbol table `db` has been created properly, and I followed every step to build and run the simulation (`verilator`) carefully as also addressed by @Kuree in https://github.com/Kuree/hgdb-debugger/issues/10#issuecomment-1233160260.
Therefore, I managed to run it from the terminal through `hgdb`. 
However, it still does not work with the vscode extension.

I configured the `launch.json` as follows:
```js
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        // hgdb
        {
            "type": "hgdb",
            "request": "launch",
            "name": "hgdb debugger",
            "program": "${workspaceFolder}/${command:AskForProgramName}",
            "runtimeIP": "0.0.0.0",
            "runtimePort": 8888
        }
    ]
}
```

Any ways to solve this?

**Comment by Kuree** [comment]
Do you have the debug db properly selected in the vscode? I don't see any breakpoint inserted in the vscode so that could be the reason? Also please make sure that you're not sharing the same debugging session with the terminal version.

I have little clue on what's going on to be honest. The vscode extension shares the same protocol as the terminal version so if one works, the other one should also work.

**Comment by rameloni** [comment]
> Do you have the debug db properly selected in the vscode? I don't see any breakpoint inserted in the vscode so that could be the reason? Also please make sure that you're not sharing the same debugging session with the terminal version.
> 
> I have little clue on what's going on to be honest. The vscode extension shares the same protocol as the terminal version so if one works, the other one should also work.

I have now tried to add some breakpoints as you suggested and it worked finally!
So the "error" was related to that, I thought that it would have displayed some values even without breakpoints.
Previously, I closed my previous terminal session, so it was not related to that.
